USE [master]
GO

/****** Object:  Database [CeverjariaZe]    Script Date: 30/11/2018 07:19:13 ******/
CREATE DATABASE [CeverjariaZe]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CeverjariaZe', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\CeverjariaZe.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CeverjariaZe_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\CeverjariaZe_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CeverjariaZe] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CeverjariaZe].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CeverjariaZe] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CeverjariaZe] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CeverjariaZe] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CeverjariaZe] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CeverjariaZe] SET ARITHABORT OFF 
GO

ALTER DATABASE [CeverjariaZe] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CeverjariaZe] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CeverjariaZe] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CeverjariaZe] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CeverjariaZe] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CeverjariaZe] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CeverjariaZe] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CeverjariaZe] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CeverjariaZe] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CeverjariaZe] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CeverjariaZe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CeverjariaZe] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CeverjariaZe] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CeverjariaZe] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CeverjariaZe] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CeverjariaZe] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CeverjariaZe] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CeverjariaZe] SET RECOVERY FULL 
GO

ALTER DATABASE [CeverjariaZe] SET  MULTI_USER 
GO

ALTER DATABASE [CeverjariaZe] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CeverjariaZe] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CeverjariaZe] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CeverjariaZe] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CeverjariaZe] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CeverjariaZe] SET QUERY_STORE = OFF
GO

USE [CeverjariaZe]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [CeverjariaZe] SET  READ_WRITE 
GO

